# Generated by Django 4.2.14 on 2024-08-06 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_type_alter_empoloyee_date_joined_empoloyee_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'Categoria',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='empoloyee',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2024, 8, 5, 19, 58, 14, 441883), verbose_name='Fecha de registro'),
        ),
        migrations.AddField(
            model_name='empoloyee',
            name='category',
            field=models.ManyToManyField(to='erp.category'),
        ),
    ]
