# Generated by Django 4.2.14 on 2024-08-06 02:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_category_alter_empoloyee_date_joined_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='names',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='names',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='empoloyee',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2024, 8, 5, 20, 31, 7, 170910), verbose_name='Fecha de registro'),
        ),
    ]
